// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Notes.DataAccess;

namespace Notes.DataAccess.Migrations
{
    [DbContext(typeof(NotesDbContext))]
    [Migration("20220608074311_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Notes.Entities.Note", b =>
                {
                    b.Property<int>("noteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("notName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noteContent")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("noteId");

                    b.ToTable("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
